Experiment_name: Skeleton_anonymization_unet

# feeder
feeder: feeders.feeder_anonymization.Feeder
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  privacy_label_path: ./data/ntu/xview/train_label_privacy.pkl
  action_label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  privacy_label_path: ./data/ntu/xview/val_label_privacy.pkl
  action_label_path: ./data/ntu/xview/val_label.pkl

# model
anonymizer_model: model.unet_model.UNet
model_args:
  n_channels: 3
  n_classes: 3
  bilinear: False

action_model: model.shift_gcn.Model
action_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

privacy_model: model.shift_gcn.Model
privacy_model_args:
  num_class: 40
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01


step: [60, 80, 100]

# training
device: [4,5,6]
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 140
nesterov: True


minimization_steps: 1

test_action:
  batch_size: 64

test_privacy:
  batch_size: 64

pretrained_action: save_models/ntu_ShiftGCN_joint_xview.pt
pretrained_privacy: save_models/ntu_experiment.pt
pretrained_privacy_test: save_models/ntu_experiment.pt

alpha: 0.3 # privacy loss
beta: 2 # recon loss

wandb: "shift_anonymization_ntu"
entity: "saemi"

dataset: "ntu60"